XCC = g++ cFlags = -std=c++11 -pthread -o signal.cpp cFiles = 
Semaphore.cpp signal.cpp hFiles = Semaphore.h ^X all: $(cFiles) 
$(hFiles)
	$(CC) $(cFlags) $(cFiles) -o signal $(DEBUGFLAGS)

DEBUG: DEBUGFLAGS = -DDEBUG
DEBUG: all

clean:
	rm *.o 
